project:
  type: website
  output-dir: docs

website:
  title: hyfzi
  page-navigation: true
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "R"
        href: R.qmd
      
  sidebar:
    - title: "R"
      style: "docked"
      background: light
      contents:
        - section: "R Base"
          href: R.qmd
          contents:
            - R.qmd
            - R1.qmd
        - section: "R plot"
          href: visnetwork.qmd
          contents:
            - visnetwork.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

